/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_Resultados;

import java.util.Random;

/**
 *
 * @author Agustin
 */
public class GUI extends javax.swing.JFrame {
    
   
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanelSlider1 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        Panel_selecionOrdenamiento = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        checkboxBubble = new javax.swing.JCheckBox();
        checkboxSelectionSort = new javax.swing.JCheckBox();
        checkboxInsertion = new javax.swing.JCheckBox();
        checkboxShell = new javax.swing.JCheckBox();
        checkboxMerge = new javax.swing.JCheckBox();
        checkboxQuick = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bComenzar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        textfieldLongitud = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        radioAleatorio = new javax.swing.JRadioButton();
        radioAscendente = new javax.swing.JRadioButton();
        radioDescendente = new javax.swing.JRadioButton();
        Panel_resultados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_intentardenuevo = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jButton1.setText("x");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 489, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Panel_selecionOrdenamiento.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Elija los metodos a comparar y presione \"Comenzar\".");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        checkboxBubble.setText("Bubble Sort");

        checkboxSelectionSort.setText("Selection Sort");

        checkboxInsertion.setText("Insertion Sort");

        checkboxShell.setText("Shell Sort");

        checkboxMerge.setText("Merge Sort");

        checkboxQuick.setText("Quick Sort");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setText("Metodos Iterativos");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setText("Metodos Recursivos");

        bComenzar.setText("Comenzar");
        bComenzar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bComenzarMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setText("Vector");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel5.setText("longitud:");

        buttonGroup1.add(radioAleatorio);
        radioAleatorio.setText("Aleatorio");

        buttonGroup1.add(radioAscendente);
        radioAscendente.setText("Ascendente");

        buttonGroup1.add(radioDescendente);
        radioDescendente.setText("Descendente");

        javax.swing.GroupLayout Panel_selecionOrdenamientoLayout = new javax.swing.GroupLayout(Panel_selecionOrdenamiento);
        Panel_selecionOrdenamiento.setLayout(Panel_selecionOrdenamientoLayout);
        Panel_selecionOrdenamientoLayout.setHorizontalGroup(
            Panel_selecionOrdenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_selecionOrdenamientoLayout.createSequentialGroup()
                .addGroup(Panel_selecionOrdenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_selecionOrdenamientoLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(Panel_selecionOrdenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(Panel_selecionOrdenamientoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(Panel_selecionOrdenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(checkboxShell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkboxInsertion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkboxBubble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkboxSelectionSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_selecionOrdenamientoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(Panel_selecionOrdenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(Panel_selecionOrdenamientoLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(Panel_selecionOrdenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkboxMerge, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(checkboxQuick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel4)
                    .addGroup(Panel_selecionOrdenamientoLayout.createSequentialGroup()
                        .addComponent(radioAleatorio)
                        .addGap(18, 18, 18)
                        .addComponent(radioAscendente))
                    .addGroup(Panel_selecionOrdenamientoLayout.createSequentialGroup()
                        .addComponent(textfieldLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(radioDescendente)))
                .addGap(86, 86, 86))
            .addGroup(Panel_selecionOrdenamientoLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(bComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Panel_selecionOrdenamientoLayout.setVerticalGroup(
            Panel_selecionOrdenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_selecionOrdenamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(Panel_selecionOrdenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_selecionOrdenamientoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(7, 7, 7)
                        .addComponent(checkboxMerge, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkboxQuick))
                    .addGroup(Panel_selecionOrdenamientoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkboxBubble)
                        .addGap(18, 18, 18)
                        .addComponent(checkboxSelectionSort)
                        .addGap(18, 18, 18)
                        .addGroup(Panel_selecionOrdenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkboxInsertion)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(Panel_selecionOrdenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkboxShell)
                            .addComponent(radioAleatorio)
                            .addComponent(radioAscendente))))
                .addGap(18, 18, 18)
                .addGroup(Panel_selecionOrdenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(radioDescendente))
                .addGap(25, 25, 25)
                .addComponent(bComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        jPanelSlider1.add(Panel_selecionOrdenamiento, "card2");

        Panel_resultados.setBackground(new java.awt.Color(153, 153, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Burbuja", null, null, null, null},
                {"Seleccion", null, null, null, null},
                {"Insercion", null, null, null, null},
                {"ShellSort", null, null, null, null},
                {"MergeSort", null, null, null, null},
                {"QuickSort", null, null, null, null}
            },
            new String [] {
                "Metodo", "Comparacion", "O.Elementales", "Movimientos", "Tiempo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 102, 102));
        jTable1.setSelectionBackground(new java.awt.Color(255, 51, 0));
        jScrollPane1.setViewportView(jTable1);

        btn_intentardenuevo.setBackground(new java.awt.Color(240, 240, 240));
        btn_intentardenuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_intentardenuevo.setForeground(new java.awt.Color(0, 0, 0));
        btn_intentardenuevo.setLabel("Volver a Intentar");
        btn_intentardenuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_intentardenuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_resultadosLayout = new javax.swing.GroupLayout(Panel_resultados);
        Panel_resultados.setLayout(Panel_resultadosLayout);
        Panel_resultadosLayout.setHorizontalGroup(
            Panel_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
            .addGroup(Panel_resultadosLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(btn_intentardenuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_resultadosLayout.setVerticalGroup(
            Panel_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_resultadosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btn_intentardenuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        jPanelSlider1.add(Panel_resultados, "card3");

        getContentPane().add(jPanelSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bComenzarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bComenzarMouseClicked
             this.jPanelSlider1.nextPanel(5,this.Panel_resultados, rootPaneCheckingEnabled);
    }//GEN-LAST:event_bComenzarMouseClicked

    private void btn_intentardenuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_intentardenuevoActionPerformed
       if(this.checkboxBubble.isSelected()){
           this.checkboxBubble.setSelected(false);
       }
       if(this.checkboxInsertion.isSelected()){
           this.checkboxInsertion.setSelected(false);
       }
       if(this.checkboxMerge.isSelected()){
           this.checkboxMerge.setSelected(false);
       }
       if(this.checkboxQuick.isSelected()){
           this.checkboxQuick.setSelected(false);
       }
       if(this.checkboxSelectionSort.isSelected()){
           this.checkboxSelectionSort.setSelected(false);
       }
       if(this.checkboxShell.isSelected()){
           this.checkboxShell.setSelected(false);
       }
       jPanelSlider1.nextPanel(5,this.Panel_selecionOrdenamiento, rootPaneCheckingEnabled);
    }//GEN-LAST:event_btn_intentardenuevoActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Panel_resultados;
    public javax.swing.JPanel Panel_selecionOrdenamiento;
    public javax.swing.JButton bComenzar;
    private java.awt.Button btn_intentardenuevo;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JCheckBox checkboxBubble;
    public javax.swing.JCheckBox checkboxInsertion;
    public javax.swing.JCheckBox checkboxMerge;
    public javax.swing.JCheckBox checkboxQuick;
    public javax.swing.JCheckBox checkboxSelectionSort;
    public javax.swing.JCheckBox checkboxShell;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    public diu.swe.habib.JPanelSlider.JPanelSlider jPanelSlider1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JRadioButton radioAleatorio;
    public javax.swing.JRadioButton radioAscendente;
    public javax.swing.JRadioButton radioDescendente;
    public javax.swing.JTextField textfieldLongitud;
    // End of variables declaration//GEN-END:variables
}
